using QuestPDF.Fluent;
using QuestPDF.Helpers;

namespace CompanyTraining.Services
{
    public class CertificatePdfGenerator
    {
        public static byte[] Generate(string employeeName, string courseTitle, DateTime completionDate, string companyName)
        {
            var document = Document.Create(container =>
            {
                container.Page(page =>
                {
                    page.Margin(50);
                    page.Size(PageSizes.A4);
                    page.PageColor(Colors.White);
                    page.DefaultTextStyle(x => x.FontSize(18));

                    page.Header()
                        .Text("Certificate of Completion")
                        .SemiBold().FontSize(30).FontColor(Colors.Blue.Medium);

                    page.Content().Column(col =>
                    {
                        col.Item().Text($"This is to certify that").Italic();
                        col.Item().Text($"{employeeName}").Bold().FontSize(24);
                        col.Item().Text($"has successfully completed the course").Italic();
                        col.Item().Text($"{courseTitle}").Bold().FontSize(22).FontColor(Colors.Green.Medium);
                        col.Item().Text($"on {completionDate:dd MMMM yyyy}");
                        col.Item().Text($"Company: {companyName}");
                    });

                    page.Footer()
                        .AlignCenter()
                        .Text("Generated by YourCompany LMS Platform");
                });
            });

            return document.GeneratePdf();
        }
    }
}
